[pyprland]
hyprland_version = "0.44.0"
plugins = [
    "layout_center",


]

[layout_center]
margin = 40
offset = [0, 20]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"